### ISSUE TITLE
Best Practice Identificatie van Organisaties, Organisatieonderdelen en voorzieningen

### ISSUE THREAD

**Issue by logius-standaardenbeheer** [Logius-standaarden/Digikoppeling-Algemeen#10]
# Wat is het issue of de wens?

Het OIN-beleid is sinds 2016 op het punt van het gebruik van SubOIns voor organisatieonderdelen en –voorzieningen verduidelijkt en uitgebreid. Het lijkt erop dat het steeds belangrijker wordt om entiteiten in een uitwisselketen te kunnen identificeren. Er bestaat tussen organisaties verschil in inzicht in de toepassing van identificatie.

Er is behoefte aan inzicht in hoe nu wordt en moet worden omgaan met identificatie in uitwisselketens tussen en met overheden.

# Wat is het resultaat?

Best practice beschrijving van Identificatie van Organisaties, Organisatieonderdelen en voorzieningen.

(Roadmap : https://logius.nl/diensten/digikoppeling/documentatie/digikoppeling-roadmap-2022-2023#index-12)

# Uitwerking

Handreiking Digikoppeling Adressering en Routering:
https://github.com/Logius-standaarden/Digikoppeling-Handreiking-Adressering-en-Routering/blob/main/main.md

**Comment by PHaasnoot** [comment]
Handreiking gepubliceerd op https://logius.nl/diensten/digikoppeling/documentatie
