### ISSUE TITLE
Voorstel uitbrengen van patch versies van documenten

### ISSUE THREAD

**Issue by logius-standaardenbeheer** [Logius-standaarden/Digikoppeling-Algemeen#11]
# Aanleiding

Na publicatie worden er soms kleine verbeterpunten ontdekt, zoals tikfouten, gebroken links of ongelukkige zinsconstructies. Om deze verbeteringen niet op te sparen voor de volgende grote release en toch van een nieuwe versienummer te kunnen voorzien, wordt gebruik gemaakt van een patchnummer. Versienummers hebben de vorm MAJOR.MINOR.PATCH

Indien er vermoeden is dat een dergelijke fout tot een andere interpretatie van de materie heeft kunnen leiden door bijvoorbeeld ambiguïteit te introduceren, zal de correctie alsnog onder Minor geschaard worden.

De huidige manier van registratie van patch releases heeft als nadeel dat elke patch meerdere mutaties oplevert in het compliance document en ook de suggestie wekt dat bij elke patch een nieuwe versie van de digikoppeling standaard wordt uitgebracht; 

# Wijziging

Daar de wijziging de inhoud niet raakt, zal de geldigheid van de huidige minor versie intact blijven. Het voorstel is om patchnummers niet meer te vermelden in de geldigheidstabellen van het normatieve document “Digikoppeling Overzicht Actuele Documentatie en Compliance”. Het patchnummer wordt vervangen met een asterisk in plaats van weggelaten om de structuur van semantisch versioneren te behouden en daarmee duidelijk te maken dat het niet enkel de .0-patchversie beslaat.

De doorgevoerde patches zullen per document in één overzichtelijke lijst op GitHub bijgehouden worden.

## Voorbeeld

> | Document                                        | Versie | Normatief | Geldig vanaf | Geldig  tot |
> | ----------------------------------------------- | ------ | --------- | ------------ | ----------- |
> | Wat is Digikoppeling                            | 1.1.*  |           | 11-04-2022   |             |
> | DK Beheermodel en releasebeleid                 | 1.5.*  |           | 19-10-2017   |             |
> | DK Architectuur                                 | 2.0.*  | X         | 11-04-2022   |             |
> | DK Koppelvlakstandaard REST API                 | 1.0.*  | X         | 11-04-2022   |             |
> | DK Koppelvlakstandaard WUS                      | 3.8.*  | X         | 11-04-2022   |             |
> | DK Koppelvlakstandaard EBMS2                    | 3.3.*  | X         | 11-04-2022   |             |
> | DK Koppelvlakstandaard Grote Berichten          | 3.8.*  | X         | 11-04-2022   |             |
> | DK Identificatie en Authenticatie               | 1.4.*  | X         | 11-04-2022   |             |
> | DK Beveiligingsstandaarden en voorschriften     | 1.4.*  | X         | 12-03-2021   |             |
> | DK Overzicht Actuele Documentatie en Compliance | 1.9.*  | X         | 11-04-2022   |             |
> | DK Best Practices WUS                           | 1.10.* |           | 11-04-2022   |             |
> | DK Best Practices EBMS2                         | 3.2.*  |           | 11-04-2022   |             |
> | DK Best Practices Grote Berichten               | 3.1.*  |           | 11-04-2022   |             |
> | DK Gebruik en achtergrond certificaten          | 1.6.*  |           | 11-04-2022   |             |
> 
> In de kolom ‘Normatief’ wordt met ‘X’ aangegeven dat het document specifieke regels bevat waar men zich aan moet houden om te voldoen aan de Digikoppeling standaard (Zie ook H5 Wanneer ben ik Digikoppeling compliant).

**Comment by sanderke** [comment]
Opgenomen in Digikoppeling Overzicht Actuele Documentatie en Compliance 1.9.1
https://github.com/Logius-standaarden/Digikoppeling-Overzicht-Actuele-Documentatie-en-Compliance/pull/2
